[project]
name = "dsarm-test"
version = "0.1.0"
description = "Test project"
readme = "README.md"
authors = [{ name = "Daniel Sarmiento", email = "dsarmiento731@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["click>=8.1.7"]

[dependency-groups]
dev = [
    { include-group = "test" },
    "isort>=7.0.0",
    "pre-commit>=4.3.0",
    "ruff>=0.14.1",
]
test = ["pytest>=8.0", "pytest-cov"]

[project.scripts]
dsarm-test = "dsarm_test.cli:cli"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."

[tool.ruff]
indent-width = 4
line-length = 120

[tool.ruff.lint]
extend-select = ["C", "I", "FAST", "RUF"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
